name: "My action"
description: "Test my action"

inputs:
  message:
    description: "The message print"
    required: true
    default: "mundo de bryan"

runs:
  using: "composite"
  
  steps:
    - name: Hola Mundo
      run: echo "Hola ${{ inputs.message }}"
      shell: bash